global: 
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs: 
  - channel: '#vsvleo-webhook'
