version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORT_WEB:-9292}:9292/tcp
    networks:
      - reddit

  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - reddit

  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
