version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORT_WEB:-9292}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net: